# Importing Required Libraries

In [37]:
import numpy as np
import pandas as pd
from collections import Counter
from imblearn.under_sampling import NearMiss


# Version 1

In [38]:
X = np.array([[1,1],[9,1],
              [2,1],[3,6],
              [4,5],[6,9]

              ])
Y= np.array([1,1,0,0,0,0])
print(Counter(Y))
data = pd.DataFrame(X)
print(data)
nm = NearMiss(n_neighbors=2,version = 1)
X_res,Y_res=nm.fit_resample(X,Y)
print(X_res)
print(Y_res)



Counter({np.int64(0): 4, np.int64(1): 2})
   0  1
0  1  1
1  9  1
2  2  1
3  3  6
4  4  5
5  6  9
[[2 1]
 [4 5]
 [1 1]
 [9 1]]
[0 0 1 1]


# Version 2

In [39]:
X = np.array([[1,1],[9,1],
              [2,1],[3,6],
              [4,5],[6,9]

              ])
Y= np.array([1,1,0,0,0,0])
print(Counter(Y))
data = pd.DataFrame(X)
print(data)
nm = NearMiss(n_neighbors=2,version = 2)
X_res,Y_res=nm.fit_resample(X,Y)
print(X_res)
print(Y_res)

Counter({np.int64(0): 4, np.int64(1): 2})
   0  1
0  1  1
1  9  1
2  2  1
3  3  6
4  4  5
5  6  9
[[2 1]
 [4 5]
 [1 1]
 [9 1]]
[0 0 1 1]


# Version 3

In [40]:
X = np.array([[1,1],[9,1],
              [2,1],[3,6],
              [4,5],[6,9]

              ])
Y= np.array([1,1,0,0,0,0])
print(Counter(Y))
data = pd.DataFrame(X)
print(data)
nm = NearMiss(n_neighbors=2,version = 3)
X_res,Y_res=nm.fit_resample(X,Y)
print(X_res)
print(Y_res)

Counter({np.int64(0): 4, np.int64(1): 2})
   0  1
0  1  1
1  9  1
2  2  1
3  3  6
4  4  5
5  6  9
[[3 6]
 [4 5]
 [1 1]
 [9 1]]
[0 0 1 1]
