# Use of Numpy

In [1]:
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr.mean())

3.0


# Use of Pandas

In [2]:
import pandas as pd
data = {"Names":['Ali' , 'Anwar' , 'Akram'] , "Age" : [20 , 22 , 23]}
df = pd.DataFrame(data)
print(df)

   Names  Age
0    Ali   20
1  Anwar   22
2  Akram   23


# Person Table

In [3]:
# import pandas as pd
# data = {"Name" : ['Saim' , 'Fazil' , 'Zohaib' , 'Abdullah'] , "Grade": ['A' , 'B' , 'A' , 'C'] , "CGPA" : [3.3 , 3.5 , 4.0 , 2.9] , "University Name " : ["ARID" , "FAST" , "BEHRIA" , "NUST"]}
# df = pd.DataFrame(data)
# print(df)

# Car Table

In [4]:
import pandas as pd
data = {"CAR Name" : ['Ferrari' , 'Tesla' , 'Dodge Challenger' , 'Lamborghini'] , "Color": ['Crystal Yellow' , 'Mad Grey' , 'Dark Chrome Red' , 'Yellow'] , "Model" : ['SF_90','Model-S','ZR_1' ,'Hurracane'] , "Mile Age " : [2.8 ,2.0 ,3.0 , 4] , "Price" : [2300000 , 5700000 , 1000000 , 11900000]}
df = pd.DataFrame(data)
print(df)

           CAR Name            Color      Model  Mile Age      Price
0           Ferrari   Crystal Yellow      SF_90        2.8   2300000
1             Tesla         Mad Grey    Model-S        2.0   5700000
2  Dodge Challenger  Dark Chrome Red       ZR_1        3.0   1000000
3       Lamborghini           Yellow  Hurracane        4.0  11900000


# Fruit Table 

In [5]:
import pandas as pd
data = {" Fruit Name" : ['Apple' , 'Banana' , 'Grapes' , 'Peach'] , "Color": ['Red' , 'Yellow' , 'Dark Purple' , 'Yellowish Orange '] , "Taste" : ['Sweet' , 'Sweet' ,'Watery Sweet' , 'Sour'] , "Shape  " : ['Cut Circle' , 'Cyllindrical ' , 'Circle' , 'Rounded Pentagon']}
df = pd.DataFrame(data)
print(df)

   Fruit Name              Color         Taste           Shape  
0       Apple                Red         Sweet        Cut Circle
1      Banana             Yellow         Sweet     Cyllindrical 
2      Grapes        Dark Purple  Watery Sweet            Circle
3       Peach  Yellowish Orange           Sour  Rounded Pentagon


# Use of Different Arrays or Lists

In [9]:
import numpy as np
list1=[2,4,6,8]
arr = np.array(list1 , dtype=float )
print(list1)
print(arr)

[2, 4, 6, 8]
[2. 4. 6. 8.]


In [10]:
import numpy as np
a1 = np.array([[2,6],[3,9]])
print(a1)


[[2 6]
 [3 9]]


In [11]:
a2=np.asarray(list1)
print(a2)

[2 4 6 8]


In [12]:
list2 = [45,134,300]
a3 = np.asarray(list2 , dtype = np.int16)
print(a3)

[ 45 134 300]


In [13]:
list3 = [45,30,-10]
a4=np.asarray(list3 , dtype=np.int32)
print(a4)

[ 45  30 -10]


In [14]:
list3=[45,30,-10]
a5=np.asarray(list3,dtype=np.int32)
print(a5)

[ 45  30 -10]


In [15]:
l3=[45,30,-10] 
a6=np.asarray(list2,dtype=np.float32) 
print(a6) 

[ 45. 134. 300.]


In [16]:
a7=np.arange(10) 
print(a7)

[0 1 2 3 4 5 6 7 8 9]


In [17]:
a8=np.arange(5,20,2) 
print(a8) 

[ 5  7  9 11 13 15 17 19]


In [18]:
a9=np.arange(3,28,3,dtype=float) 
print(a9) 

[ 3.  6.  9. 12. 15. 18. 21. 24. 27.]


In [19]:
a10=np.zeros((5,8)) 
print(a10) 

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [20]:
a11=np.ones((3,7)) 
print(a11)

[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]


In [21]:
a12=np.array([3,1,7,8,9,10,11,56,7,2,4]) 
a13=a12[:6] 
a13=a13+1 
print(a12) 
print(a13) 

[ 3  1  7  8  9 10 11 56  7  2  4]
[ 4  2  8  9 10 11]


- creating series from a list using default index 

In [22]:
a = [1, 7, 2] 
myvar = pd.Series(a) 
print(myvar) 
print(myvar[0]) 

0    1
1    7
2    2
dtype: int64
1


- creating series from a list with custom indexes 

In [23]:
a = [1, 7, 2] 
myvar = pd.Series(a, index=["x","y","z"]) 
print(myvar['x']) 

1


- creating series with a dictionary 

In [24]:
calories={"day1":420,"day2":380,"day3":390} 
myvar = pd.Series(calories) 
print(myvar) 

day1    420
day2    380
day3    390
dtype: int64


In [25]:
 
calories={"day1": 420, "day2":380,"day3":390} 
myvar=pd.Series(calories,index=["day1","day2"]) 
print(myvar) 

day1    420
day2    380
dtype: int64


- creating dataframe with a dictionary

In [26]:
df=pd.DataFrame({'Name':['Ali','Aaliya','Zaid'], 
              'Age':[22,21,23], 
             'Gender':['male','female','male']}) 
print(df) 

     Name  Age  Gender
0     Ali   22    male
1  Aaliya   21  female
2    Zaid   23    male


- printing only 1 column of a dataframe

In [27]:
print(df['Age']) 

0    22
1    21
2    23
Name: Age, dtype: int64


- shows a quick statistic summary of your data 

In [28]:
print(df.describe()) 

        Age
count   3.0
mean   22.0
std     1.0
min    21.0
25%    21.5
50%    22.0
75%    22.5
max    23.0


- printing maximum value of a column 

In [29]:
print(df['Age'].max()) 

23


- reading cvs files using pandas 

In [31]:
titanic = pd.read_csv("train_and_test2.csv")

- to view last 4 row of your data 

In [32]:
t=titanic.tail(4) 
print(t) 

      Passengerid   Age      Fare  Sex  sibsp  zero  zero.1  zero.2  zero.3  \
1305         1306  39.0  108.9000    1      0     0       0       0       0   
1306         1307  38.5    7.2500    0      0     0       0       0       0   
1307         1308  28.0    8.0500    0      0     0       0       0       0   
1308         1309  28.0   22.3583    0      1     0       0       0       0   

      zero.4  ...  zero.12  zero.13  zero.14  Pclass  zero.15  zero.16  \
1305       0  ...        0        0        0       1        0        0   
1306       0  ...        0        0        0       3        0        0   
1307       0  ...        0        0        0       3        0        0   
1308       0  ...        0        0        0       3        0        0   

      Embarked  zero.17  zero.18  2urvived  
1305       0.0        0        0         0  
1306       2.0        0        0         0  
1307       2.0        0        0         0  
1308       0.0        0        0         0  

[4 rows

-  to view first 8 row of your data 

In [33]:
h=titanic.head(8) 
print(h) 

   Passengerid   Age     Fare  Sex  sibsp  zero  zero.1  zero.2  zero.3  \
0            1  22.0   7.2500    0      1     0       0       0       0   
1            2  38.0  71.2833    1      1     0       0       0       0   
2            3  26.0   7.9250    1      0     0       0       0       0   
3            4  35.0  53.1000    1      1     0       0       0       0   
4            5  35.0   8.0500    0      0     0       0       0       0   
5            6  28.0   8.4583    0      0     0       0       0       0   
6            7  54.0  51.8625    0      0     0       0       0       0   
7            8   2.0  21.0750    0      3     0       0       0       0   

   zero.4  ...  zero.12  zero.13  zero.14  Pclass  zero.15  zero.16  Embarked  \
0       0  ...        0        0        0       3        0        0       2.0   
1       0  ...        0        0        0       1        0        0       0.0   
2       0  ...        0        0        0       3        0        0       2.0   


- Display all entries of a specific column 

In [34]:
ages = titanic["Age"] 
ages.head() 

0    22.0
1    38.0
2    26.0
3    35.0
4    35.0
Name: Age, dtype: float64

- applying selection criteria on a column 

In [35]:
above_35 = titanic[titanic["Age"] > 35] 
print(above_35.head())

    Passengerid   Age     Fare  Sex  sibsp  zero  zero.1  zero.2  zero.3  \
1             2  38.0  71.2833    1      1     0       0       0       0   
6             7  54.0  51.8625    0      0     0       0       0       0   
11           12  58.0  26.5500    1      0     0       0       0       0   
13           14  39.0  31.2750    0      1     0       0       0       0   
15           16  55.0  16.0000    1      0     0       0       0       0   

    zero.4  ...  zero.12  zero.13  zero.14  Pclass  zero.15  zero.16  \
1        0  ...        0        0        0       1        0        0   
6        0  ...        0        0        0       1        0        0   
11       0  ...        0        0        0       1        0        0   
13       0  ...        0        0        0       3        0        0   
15       0  ...        0        0        0       2        0        0   

    Embarked  zero.17  zero.18  2urvived  
1        0.0        0        0         1  
6        2.0        0   

- selecting more than one columns 

In [36]:
print(titanic[["Age", "Fare"]])

       Age      Fare
0     22.0    7.2500
1     38.0   71.2833
2     26.0    7.9250
3     35.0   53.1000
4     35.0    8.0500
...    ...       ...
1304  28.0    8.0500
1305  39.0  108.9000
1306  38.5    7.2500
1307  28.0    8.0500
1308  28.0   22.3583

[1309 rows x 2 columns]


- display first 3 rows of data 

In [37]:
print(titanic[0:3]) 

   Passengerid   Age     Fare  Sex  sibsp  zero  zero.1  zero.2  zero.3  \
0            1  22.0   7.2500    0      1     0       0       0       0   
1            2  38.0  71.2833    1      1     0       0       0       0   
2            3  26.0   7.9250    1      0     0       0       0       0   

   zero.4  ...  zero.12  zero.13  zero.14  Pclass  zero.15  zero.16  Embarked  \
0       0  ...        0        0        0       3        0        0       2.0   
1       0  ...        0        0        0       1        0        0       0.0   
2       0  ...        0        0        0       3        0        0       2.0   

   zero.17  zero.18  2urvived  
0        0        0         0  
1        0        0         1  
2        0        0         1  

[3 rows x 28 columns]


- display all rows of specific columns 

In [38]:
val=titanic.loc[:, ["Age", "Survived"]] 
print(val)

KeyError: "['Survived'] not in index"

- instead of column/rows names we can use integer 
locations 

In [39]:
col3=titanic.iloc[3] 
print(col3) 

Passengerid     4.0
Age            35.0
Fare           53.1
Sex             1.0
sibsp           1.0
zero            0.0
zero.1          0.0
zero.2          0.0
zero.3          0.0
zero.4          0.0
zero.5          0.0
zero.6          0.0
Parch           0.0
zero.7          0.0
zero.8          0.0
zero.9          0.0
zero.10         0.0
zero.11         0.0
zero.12         0.0
zero.13         0.0
zero.14         0.0
Pclass          1.0
zero.15         0.0
zero.16         0.0
Embarked        2.0
zero.17         0.0
zero.18         0.0
2urvived        1.0
Name: 3, dtype: float64


In [40]:
 
rec=titanic.iloc[[1, 2, 4], [0, 2]] 
print(rec) 

   Passengerid     Fare
1            2  71.2833
2            3   7.9250
4            5   8.0500


In [41]:
rec1=titanic.iloc[3:8, 0:4] 
print(rec1) 

   Passengerid   Age     Fare  Sex
3            4  35.0  53.1000    1
4            5  35.0   8.0500    0
5            6  28.0   8.4583    0
6            7  54.0  51.8625    0
7            8   2.0  21.0750    0
